name: Build Android App using GitHub Actions

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用Ubuntu系统镜像

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 拉取你的代码

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8' # 根据项目需要设置Java版本，如8、11等

      - name: Change wrapper permissions
        run: chmod +x ./gradlew # 确保Gradle包装器脚本有执行权限

      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug --stacktrace # 执行调试版本的编译

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk # 上传生成的APK文件
